# Generated by Django 3.2.5 on 2022-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
